day2 mvc/Controllers/workController.cs
using day2_mvc.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace day2_mvc.Controllers
{
    public class workController : Controller
    {
        private CompanyDbContext context;
        public workController()
        {
            context = new CompanyDbContext();
        }
        //get all
        public IActionResult Index()
        {
            List<Works_For> works = context.WorkFor.Include(e => e.employee).Include(p => p.project).ToList();
            // Create ViewBag to store colors
            List<string> colors = new List<string>();
            foreach (var work in works)
            {
                if (work.Hours > 50)
                {
                    colors.Add("green");

                }
                else
                {
                    colors.Add("red");
                }
            }

            ViewBag.Colors = colors;

            return View(works);
        }
        //get By Id
        public IActionResult Details(int id)
        {
            Employee employee = context.Employees .SingleOrDefault(e => e.Id == id);

            if (employee == null)
            {
                return NotFound();
            }

            List<Works_For> worksForList = context.WorkFor.Include(p => p.project)
                                              .Where(w => w.ESSN== id)
                                              .ToList();

            ViewBag.EmployeeName = $"{employee.Fname} {employee.Lname}";
            List<string> colors = new List<string>();
            foreach (var work in worksForList)
            {
                if (work.Hours > 50)
                {
                    colors.Add("green");

                }
                else
                {
                    colors.Add("red");
                }
            }

            ViewBag.Colors = colors;

            return View(worksForList);
        }
        //======================================================================
        //edit operaion
        public IActionResult Edit(int id)
        {
            Employee emp = context.Employees.Where(p => p.Id == id).SingleOrDefault();
            List<Project> project = context.WorkFor.Include(w => w.project).Where(w => w.ESSN == id).Select(p => p.project).ToList();

            ViewBag.project = project;
            ViewBag.employee = emp;
            return View();
        }
        public IActionResult EditDB(Works_For works)
        {
            context.WorkFor.Update(works);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult editscript(int id, int ssn)
        {
            Works_For hours = context.WorkFor.Where(w => w.Pno == id && w.ESSN == ssn).FirstOrDefault();

            return PartialView("_editpartial", hours);

        }
    }
}

day2 mvc/Views/work/Details.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    int i = 1;
}
@model List<Works_For>

<h2>Works For Details for @ViewBag.EmployeeName</h2>
<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Project Name</th>
            <th scope="col">Hours</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@(i++)</td>
                <td>@item.project.Pname</td>
                <td style="color: @ViewBag.Colors[i-2]">@item.Hours</td>
            </tr>
        }
    </tbody>
</table>

<a href="/work/Index">Back to Works For List</a>

day2 mvc/Views/work/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model Works_For
@{
    SelectList list = new SelectList(ViewBag.project, "Pnumber", "Pname");
    Employee emp = ViewBag.employee;


}


<h2>Edit Works_for</h2>

<form asp-action="EditDB" asp-controller="work">
    <input hidden asp-for="ESSN" value="@ViewBag.employee.Id" />
    <div class="form-group">
        <label class="control-label">first name</label>
        <input value="@ViewBag.employee.Fname" class="form-control" />
    </div>

    <div class="form-group">
        <label class="control-label">last name</label>
        <input value="@ViewBag.employee.Lname" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="Pno" class="control-label">Project</label>
        <select asp-for="Pno" asp-items="list" class="form-select" onchange="gethour(this.value,@emp.Id)"></select>
    </div>
    <div class="form-group" id="hh">
    </div>
    <button class="btn btn-primary" type="submit">Edit</button>
</form>
@section scripts {
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/java.js"></script>
}

day2 mvc/Views/work/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    int i = 1;

}
@model List<Works_For>

<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Employee Name</th>
            <th scope="col">Project Name</th>
            <th scope="col">Hours</th>
            <th scope="col">More Details</th>
            <th scope="col">Edit</th>
@*             <th scope="col">Delete</th>
 *@        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <th scope="row">@(i++)</th>
                <td>@item.employee .Fname @item.employee.Lname</td>
                <td>@item.project.Pname</td>
                <td style="color:@ViewBag.Colors[i-2]">@item.Hours</td>
                <td><a href="/work/Details/@item.ESSN"><i class="fa-solid fa-circle-info"></i></a></td>
                <td><a asp-action="Edit" asp-controller="work" asp-route-id="@item.ESSN" class="btn btn-primary">Edit</a> </td>
@*                 <td><a asp-action="Delete" asp-controller="worksfor" class="btn btn-danger">Delete</a> </td>
 *@
            </tr>
        }  
    </tbody>
</table>

@* @section Slide_title {
    All Works For
} *@