day2 mvc/Controllers/EmployeelistController.cs
using day2_mvc.Models;
using day2_mvc.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace day2_mvc.Controllers
{
    public class EmployeelistController : Controller
    {

        CompanyDbContext context = new CompanyDbContext();


        public IActionResult Index()
        {
            List<Employee> employees = context.Employees.ToList();
            return View(employees);
        }



        [HttpGet]
        public IActionResult Add()
        {
           

            EmployeeVM empVM = new EmployeeVM()
            {
                departments = new SelectList(context.Departments, nameof(Departments.Id), nameof(Departments.Dname))
            };
            return View(empVM);

        }


        [HttpPost]
        [ValidateAntiForgeryToken]

        public IActionResult Add(EmployeeVM empVM)
        {
            

            if (ModelState.IsValid)
            {
                Employee employee = new Employee()
                {
                   
                    Fname = empVM.Fname,
                    Lname = empVM.Lname,
                    Address = empVM.Address,
                    Salary = empVM.Salary,
                    Dno = empVM.Dno,
                };
                context.Employees.Add(employee);
                context.SaveChanges();
                return RedirectToAction("Index");
            }
          
            List<Departments> departments = context.Departments.ToList();
            empVM.departments = new SelectList(departments, nameof(Departments.Id), nameof(Departments.Dname));
            return View(empVM);


        }
    }
}

day2 mvc/Views/Employeelist/Add.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@using day2_mvc.ViewModels;
@model EmployeeVM

<form asp-action="Add" asp-controller="Employeelist" method="post">
   
    <div>
        <label asp-for="Fname" class="form-label"></label>
        <input asp-for="Fname" class="form-control" />
        <span asp-validation-for="Fname" class="text-danger"></span>
    </div>
    <div>
        <label asp-for="Lname" class="form-label"></label>
        <input asp-for="Lname" class="form-control" />
        <span asp-validation-for="Lname" class="text-danger"></span>
    </div>
    <div>
        <label asp-for="Address" class="form-label"></label>
        <input asp-for="Address" class="form-control" />
        <span asp-validation-for="Address" class="text-danger"></span>

    </div>
    <div>
        <label asp-for="Salary" class="form-label"></label>
        <input asp-for="Salary" class="form-control" />
        <span asp-validation-for="Salary" class="text-danger"></span>

    </div>
    <div>
        <label asp-for="Email" class="form-label"></label>
        <input asp-for="Email" class="form-control" />
        <span asp-validation-for="Email" class="text-danger"></span>

    </div>
    <div>
        <label asp-for="Password" class="form-label"></label>
        <input asp-for="Password" class="form-control" />
        <span asp-validation-for="Password" class="text-danger"></span>

    </div>
    <div>
        <label asp-for="ConfirmPassword" class="form-label"></label>
        <input asp-for="ConfirmPassword" class="form-control" />
        <span asp-validation-for="ConfirmPassword" class="text-danger"></span>

    </div>
    <div>
        <label asp-for="Dno" class="form-label"></label>
   
        <select asp-for="Dno" asp-items="Model.departments" class="form-control">
        </select>
        <span asp-validation-for="Dno" class="text-danger"></span>

    </div>
    <input type="submit" value="Add" />

</form>
@section Scripts {
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

day2 mvc/Views/Employeelist/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    int i = 0;
}

@model List<Employee>



<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Fname</th>
            <th scope="col">Lname</th>
            <th scope="col">Salary</th>
            <th scope="col">address</th>
            <th scope="col">Handle</th>
        </tr>
    </thead>
    <tbody>
        @foreach (Employee std in Model)
        {
            <tr>
                <th scope="row">@(++i)</th>
                <td>@std.Fname</td>
                <td>@std.Lname</td>
                <td>@std.Salary</td>
                <td>@std.Address</td>
                
                <td>
                  
                    | <a>Edit</a>
                    | <a>Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<button type="submit" class="btn btn-primary"><a asp-action="Add" asp-controller="Employeelist">Add New Employee</a></button>